name: Docker Deploy Action

description: >
  🪂  A Github Action to deploy pages

branding:
  icon: 'command'
  color: 'yellow'

inputs:
  docker_hub_username:
    description: Username for Docker Hub
    default: ${{ github.actor }}
    required: false
  docker_hub_password:
    description: Docker Hub password
    required: true
  docker_hub_token:
    description: Docker Hub authentication token
    required: true
  credentials:
    description: The Google cloud credentials
    required: true
  token:
    description: The Github personal token
    required: true

runs:
  using: composite
  steps:
    - name: Initial action
      if: runner.os == 'Linux'
      uses: ./.github/actions/1-ubuntu/1-maps/1-init@main
      with:
        actor: ${{ github.actor }}
        token: ${{ inputs.token }}

    - name: Target Configuration
      if: runner.os == 'Linux'
      uses: ./.github/actions/1-ubuntu/1-maps/2-build@main
      with:
        hub_username: ${{ inputs.docker_hub_username }}
        hub_password: ${{ inputs.docker_hub_password }}
        hub_token: ${{ inputs.docker_hub_token }}
        action_path: ${{ github.action_path}}

    - name: Profiling Feedback
      if: runner.os == 'Windows'
      uses: ./.github/actions/2-windows/1-maps/1-init@main
      with:
        token: ${{ inputs.token }}
        action_path: ${GITHUB_ACTION_PATH//\\//}
        hub_username: ${{ inputs.docker_hub_username }}
        hub_token: ${{ inputs.docker_hub_token }} 
